name: cato_feed
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 0.1.3+6

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^6.0.0
  meta: ^1.1.8
  get_it: ^4.0.4
  injectable: ^1.0.2 #Code Generator for get_it
  json_annotation: ^3.0.1
  kt_dart: ^0.7.0+1
  auto_route: ^0.6.7
  cupertino_icons: ^0.1.3
  freezed_annotation: ^0.11.0+1
  google_sign_in: ^4.5.1
  flutter_platform_widgets: ^0.60.1
  youtube_player_webview: ^1.0.0+1
  flutter_staggered_grid_view: ^0.3.2
  flutter_tindercard: ^0.2.0
  dots_indicator: ^1.2.0
  moor: ^3.3.1
  sqlite3_flutter_libs: ^0.2.0
  path_provider: ^1.6.14
  path: ^1.7.0
  graphql: ^3.1.0
  connectivity: '>=0.4.9+2 <2.0.0'
  firebase_core: ^0.5.0
  firebase_analytics: ^6.0.0
  firebase_crashlytics: ^0.1.4+1
  firebase_dynamic_links: ^0.6.0
  firebase_messaging: ^7.0.0
  shared_preferences: '>=0.5.10 <2.0.0'
  flushbar: ^1.10.4
  url_launcher: 5.5.2
  share: '>=0.6.5 <2.0.0'
  get_version: ^0.2.2
  infinite_scroll_pagination: ^1.0.0+2
  auto_size_text: ^2.1.0
  flutter_blurhash: ^0.5.0
  app_usage: ^1.0.1
  device_apps: ^1.2.0
  app_blocker:
    path: ./app_blocker
  lottie: ^0.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: 
  injectable_generator: ^1.0.2
  freezed: ^0.11.5
  auto_route_generator: ^0.6.8
  moor_generator: ^3.3.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/images/debug/
    - assets/images/
    - assets/images/2.0x/
    - assets/images/3.0x/

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Light.ttf
          weight: 300
        - asset: assets/fonts/Roboto-Regular.ttf
          weight: 400
        - asset: assets/fonts/Roboto-Medium.ttf
          weight: 500
    - family: SFProDisplay
      fonts:
        - asset: assets/fonts/SFProDisplay-Thin.ttf
          weight: 300
        - asset: assets/fonts/SFProDisplay-Regular.ttf
          weight: 400
        - asset: assets/fonts/SFProDisplay-Semibold.ttf
          weight: 500
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
