name: feed
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  # stacked state management
  stacked: ^2.1.1
  stacked_services: ^0.8.5

  # data models
  freezed_annotation: ^0.14.1
  json_annotation: ^4.0.1

  # checks connectivity - [mobile][wifi][offline]
  connectivity: ^3.0.3
  logger: ^1.0.0
  hive: ^2.0.4
  path_provider: ^2.0.1
  graphql: ^5.0.0-nullsafety.4
  flutter_dotenv: ^4.0.0-nullsafety.1
  package_info: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # code generators
  build_runner: ^2.0.2
  stacked_generator: ^0.4.1
  hive_generator: ^1.1.0

  # data models
  freezed: ^0.14.1+3
  json_serializable: ^4.1.1

flutter:
  uses-material-design: true

  assets:
    - .env

  fonts:
    - family: Archivo
      fonts:
        - asset: assets/fonts/Archivo-Regular.ttf
          weight: 400
        - asset: assets/fonts/Archivo-Medium.ttf
          weight: 500
        - asset: assets/fonts/Archivo-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Archivo-Bold.ttf
          weight: 700
