name: feed
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  # stacked state management
  stacked: ^2.1.1
  stacked_services: ^0.8.5
  observable_ish: ^3.0.0

  # data models
  freezed_annotation: ^0.14.1
  json_annotation: ^4.0.1

  # logger for debugging
  logger: ^1.0.0

  # checks connectivity - [mobile][wifi][offline]
  connectivity: ^3.0.3

  # A secure internal NoSQL Database
  hive: ^2.0.4
  path_provider: ^2.0.1

  # graphql for fetching data from API
  graphql: ^5.0.0-nullsafety.4

  # could be handy for hiding keys in [.env] file
  flutter_dotenv: ^4.0.0-nullsafety.1

  # fetches [version][build-info]..
  package_info: ^2.0.0

  # a videoplayer to play youtube videos
  youtube_player_flutter: ^8.0.0

  # firebase integration
  firebase_auth: ^1.1.4
  stacked_firebase_auth: ^0.2.5
  firebase_core: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  # code generators
  build_runner: ^2.0.2
  stacked_generator: ^0.4.1
  hive_generator: ^1.1.0

  # data models
  freezed: ^0.14.1+3
  json_serializable: ^4.1.1

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/images/

  fonts:
    - family: AppFont
      fonts:
        - asset: assets/fonts/Regular.otf
          weight: 400
        - asset: assets/fonts/Medium.otf
          weight: 500
        - asset: assets/fonts/Semibold.otf
          weight: 600
        - asset: assets/fonts/Bold.otf
          weight: 700
        - asset: assets/fonts/Heavy.otf
          weight: 800
        - asset: assets/fonts/Black.otf
          weight: 900
