name: Fastlane Setup

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    env:
      PLAY_STORE_SIGNING: ${{ secrets.PLAY_STORE_SIGNING }}

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: import key.properties
        run: cd ./android && echo '${{ secrets.PLAY_STORE_SIGNING }}' > key.properties

      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - uses: subosito/flutter-action@v1
        with:
          flutter-version: "2.0.6"

      - run: flutter doctor -v

      - run: flutter pub get

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "2.6"
          bundler-cache: true
          working-directory: android

      - run: bundle exec fastlane beta
        env:
          PLAY_STORE_CONFIG_JSON: ${{ secrets.PLAY_STORE_CONFIG_JSON }}
        working-directory: android

      # - run: flutter build appbundle

      # - run: flutter test
